### ISSUE TITLE
RRF3: Z position display changes when heightmaps load/unload.

### ISSUE THREAD

**Issue by gtjoseph** [Duet3D/RepRapFirmware#343]
Without heightmap it loaded: Z` "machinePosition" : 15.200,`
The heightmap shows "0.145" for that specific XY location. so...
With the heightmap loaded: Z` "machinePosition" : 15.055,`
This with all axes at a standstill.

What's more, with the heightmap loaded, when the XY axes are moving but the Z axis is not, the reported Z position changes depending on the heightmap correction for the XY location the carriage is traversing.

This was never the case with RRF2.

**Comment by Nibbels** [comment]
My post does not refer to the absolute same topic but It might be the same cause.
I did not want to open a second issue while this is stalled and unanswered. My issue would be:

"**RRF3: Z position display changes when changing a tool or pausing on a Toolchanger. The added Z offset is tool dependend and height map dependend. Pausing and unpausing cumulates the offsets**."

I documented my path towards my current knowledge here:
https://forum.e3d-online.com/threads/layer-heights-different-between-tools.3637/

This evening I recorded the video. It was the first try to make the movie. Sorry for the noise and uncoordinated guidance. But It is already late and I didnt want to delay this topic by making the absolute perfect video.
https://www.youtube.com/watch?v=VqTbf3GnA2o

Config and all the steps(commits) towards this config is found here:
https://github.com/Nibbels/e3d-toolchanger-config/tree/master
Just before posting this I refreshed all the content to be equal to my printers files.

The test part is uploaded as well: "3HeartTestTeil - T0-285 T1-285 T2-175 - use dryrun.gcode"
It has been created using simplify 3D. I use hardware retraction and filament configurations as seen within the githubs configuration.

**Comment by Billtopia** [comment]
For the tool change you should be able to undo the tool offsets in the tfreeN.g file

**Comment by Nibbels** [comment]
The bug seems to be gone when I dont use bed leveling.

Today I removed all the filament.
Then I manually pressed the Z endstop to print into the air.
And started the same print again.

https://youtu.be/osxBDhneF1M

What you see within the Video: The bug is gone and the physical offsets seem to be fine.
Changes are:
![image](https://user-images.githubusercontent.com/3265671/78829905-71179a80-79e7-11ea-8a13-e798e256d560.png)
![image](https://user-images.githubusercontent.com/3265671/78829915-75dc4e80-79e7-11ea-814e-74cbe6c6240e.png)
![image](https://user-images.githubusercontent.com/3265671/78829935-7c6ac600-79e7-11ea-8567-b4418e548b54.png)
![image](https://user-images.githubusercontent.com/3265671/78829949-82f93d80-79e7-11ea-84d8-b40ab4ec0279.png)
![image](https://user-images.githubusercontent.com/3265671/78829963-87bdf180-79e7-11ea-9c49-6b2dc513c22c.png)
![image](https://user-images.githubusercontent.com/3265671/78829984-8d1b3c00-79e7-11ea-9456-9d6919d18eb6.png)
![image](https://user-images.githubusercontent.com/3265671/78830007-93a9b380-79e7-11ea-933a-9d5fd022cb4b.png)
![image](https://user-images.githubusercontent.com/3265671/78830024-9a382b00-79e7-11ea-89bb-202248283cad.png)
![image](https://user-images.githubusercontent.com/3265671/78830041-a02e0c00-79e7-11ea-8326-06383275fe6c.png)

In case someone thinks what ;G1 R2 Z0 has to do within tpostN.g: I previously added this as another test and it did not change my problem.
I once found that here: https://forum.duet3d.com/topic/9347/tool-offset-ignored-z-axis

**Comment by Nibbels** [comment]
To return to the buggy behaviour I added 
G29 S1 ; Use the Z offset Mesh Map on the SD card
into start.g again.
![image](https://user-images.githubusercontent.com/3265671/78833046-88a55200-79ec-11ea-8dda-e1c9bccb1a68.png)
And I put a measurement device on the bed.
![image](https://user-images.githubusercontent.com/3265671/78833149-aecaf200-79ec-11ea-83ef-715385a76e75.png)

And thats the full video which shows the behaviour and all the detailed z problems:
- pausing
- toolchanging
- correction at G1 Zxxx / layer change

https://youtu.be/aEVe9OVEAUo

**Comment by Nibbels** [comment]
My issue seems to be solved with RRF 3.01 **RC11**

See here: https://forum.e3d-online.com/threads/layer-heights-different-between-tools.3637/page-3#post-36633 and prior.

And see
https://github.com/dc42/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md
Bug fixes:
"Pause and resume sometimes caused a small Z shift if bed compensation was in use and the tool had an X or Y offset"
That bugfix as well fixed the tool change offset I reported.

@gtjoseph did your problem vanish with this version too?

In case we both (@gtjoseph) had the same kind of issue we probably can close this issue now.

**Comment by Nibbels** [comment]
https://github.com/dc42/RepRapFirmware/commit/5dda6c9d5aaa24ea94f9246db73e702580e5d0dc
